apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-2019-with-logging
  labels:
    app: iis-2019
spec:
  replicas: 1
  template:
    metadata:
      name: iis-2019-with-logging
      labels:
        app: iis-2019
        logging: enabled
    spec:
      containers:
      - name: iis
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        resources:
          limits:
            cpu: 1
            memory: 800m
          requests:
            cpu: .1
            memory: 300m
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: C:\inetpub\logs\LogFiles\w3svc1
          name: log-volume
      - name: fluentd
        image: jjdelorme/fluentd-win:1.3
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: C:\logs
          name: log-volume
      volumes:
      - name: log-volume
        emptyDir: {}
      nodeSelector:   # selects only a windows node
        "beta.kubernetes.io/os": windows
      tolerations:    # required because the windows node is tainted such that non-windows containers don't get scheduled 
      - key: beta.kubernetes.io/os
        operator: Equal
        value: "windows"
  selector:
    matchLabels:
      app: iis-2019        
      logging: enabled